[package]
name = "no-error-type"
version = "0.1.2"
edition = "2021"
license = "CC0-1.0"
description = "Error type for no error"

[dependencies]
embedded-hal = { version = "1.0.0", optional = true }
embedded-io = { version = "0.6.1", optional = true }

[features]
embedded-io = ["dep:embedded-io"]
embedded-hal = ["dep:embedded-hal"]
